// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function Create(arg1:database.Carga):Promise<{[key: string]: any}>;

export function Delete(arg1:number):Promise<{[key: string]: any}>;

export function GetAll():Promise<Array<database.Carga>>;

export function GetOne(arg1:number):Promise<database.Carga>;

export function Update(arg1:number,arg2:database.Carga):Promise<{[key: string]: any}>;
