// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['database']['Carga']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['database']['Carga']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['database']['Carga']['GetAll']();
}

export function GetOne(arg1) {
  return window['go']['database']['Carga']['GetOne'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['database']['Carga']['Update'](arg1, arg2);
}
