// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['database']['Docente']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['database']['Docente']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['database']['Docente']['GetAll']();
}
