// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function Create(arg1:database.PNF):Promise<{[key: string]: any}>;

export function GetAll():Promise<Array<database.PNF>>;
